### ISSUE TITLE
最近重装发现无法显示背景了

### ISSUE THREAD

**Issue by sai2333** [AlanLi7991/fuwafuwa-background#6]
如题，我记得以前安装后只要确认是管理员启动编辑器就可以了。但现在好像不行了，我重装了几次，也使用了自定义模式（请问自定义模式使用的库文件是resource/addon/darwin/xxx.node吗？）
![image](https://user-images.githubusercontent.com/27514272/146158494-a9c34df2-3e9f-4c57-880d-8f47c25213fd.png)
谢谢作者抽空解答。

**Comment by AlanLi7991** [comment]
emmm 应该是太久没维护了，VSCode本身升级改了部分路径吧，我抽空维护下，好了在这里回复你

**Comment by icahnchen** [comment]
我也是遇到了 同样的问题

**Comment by AlanLi7991** [comment]
更新了 有空的话麻烦帮忙测测 有问题可以留言
